-- The Commons: Supabase schema
-- Run this in Supabase SQL Editor.
-- Uses only the publishable client key from config.js; NEVER put a service-role key in the browser.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  save_key text not null default 'main',
  game_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(user_id, save_key)
);

create table if not exists public.news_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  report_date date not null,
  headline text not null,
  report_text text not null,
  player_choice text,
  voter_reaction integer,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.game_saves enable row level security;
alter table public.news_reports enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "saves own rows" on public.game_saves;
create policy "saves own rows" on public.game_saves
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "reports own rows" on public.news_reports;
create policy "reports own rows" on public.news_reports
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Optional helper to create/update a profile after Discord login.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Player'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do update set
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
